name: Test AoC 2021
on: [push]
jobs:
  Test-AoC-2021:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking out ${{ github.ref }} from ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DATA_PAT }}
          submodules: recursive
      - name: Run node -v
        run: node -v
      - name: Run npm install
        run: npm install
      - name: Run test
        run: npm run test
